package com.deds.morph.gametest.neoforge;

import net.fabricmc.fabric.api.gametest.v1.CustomTestMethodInvoker;
import net.fabricmc.fabric.api.gametest.v1.GameTest;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Vec3i;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructurePlaceSettings;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;

import java.lang.reflect.Method;
import java.util.Optional;

/**
 * Gametests of the NeoForge test harness itself, NeoForge only (listed in
 * {@code deds_morph_test/gametest-classes-neoforge.txt}): what the shared
 * tests take for granted from Fabric's harness has to be checked here, where
 * this project supplies it.
 */
public final class NeoForgeHarnessGameTests implements CustomTestMethodInvoker {

    private static final Identifier EMPTY = Identifier.fromNamespaceAndPath(
            "fabric-gametest-api-v1", "empty");

    /**
     * Every shared test runs in Fabric's default structure,
     * {@code fabric-gametest-api-v1:empty}: 8x8x8 blocks, all 512 of them air.
     * Fabric API ships it as an SNBT file only its own loader reads; on
     * NeoForge this project ships the same structure as a plain structure NBT
     * ({@code data/fabric-gametest-api-v1/structure/empty.nbt}, generated by
     * {@code neoforge/tools/gen_empty_structure.py}). A malformed file would
     * NOT fail loudly: {@code StructureTemplate.load} reads {@code size} and
     * each {@code pos} as int LISTS with defaults, so an int ARRAY there reads
     * as size 0,0,0 with 512 air blocks piled on the origin, and every test's
     * bounds, clearing and barrier ceiling would quietly change. So: the
     * loaded template is exactly 8x8x8 and holds exactly 512 air blocks.
     */
    @GameTest(maxTicks = 20)
    public void fabricEmptyStructureIsEightCubedAir(GameTestHelper helper) {
        Optional<StructureTemplate> loaded =
                HarnessCompat.structures(helper.getLevel()).get(EMPTY);
        helper.assertTrue(loaded.isPresent(),
                "the structure " + EMPTY + " must load (the shared tests' default)");
        StructureTemplate template = loaded.get();
        helper.assertTrue(template.getSize().equals(new Vec3i(8, 8, 8)),
                EMPTY + " must be 8x8x8 but is " + template.getSize());
        int air = template.filterBlocks(BlockPos.ZERO, new StructurePlaceSettings(),
                Blocks.AIR).size();
        helper.assertTrue(air == 512,
                EMPTY + " must hold 512 air blocks but holds " + air);
        helper.succeed();
    }

    @Override
    public void invokeTestMethod(GameTestHelper context, Method method)
            throws ReflectiveOperationException {
        method.invoke(this, context);
    }
}
